yect/bankbook/urls.py
from django.urls import path, re_path

from . import views

app_name = "bankbook"
urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('',
         views.statements,
         name='statements'),
    path('new',
         views.edit_account,
         name='new_account'),
    path('edit/<str:account_type><int:account_id>',
         views.edit_account,
         name='edit_account'),
    re_path(r'^upload/(?P<account_type>[a]{1})(?P<account_id>[0-9]+)$',
            views.upload_statements,
            name='upload_statements'),
    re_path(r'^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)$',
            views.account_summary,
            name='account_summary'),
    re_path(r'^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)$',
            views.account_summary,
            name='account_summary'),
    # path('csummarya/', views.cum_summary_year, name='cumulative_a'),
    # path('csummarya/<int:year>', views.cum_summary_year, name='cumulative_a'),
    # path('csummary/<int:year>', views.cum_summary_month, name='cumulative'),
    # path('csummary/<int:year>/<int:month>', views.cum_summary_month, name='cumulative'),
    # path('tsummarya/<int:account_id>', views.type_summary_year, name='typea'),
    # path('tsummarya/<int:account_id>/<int:year>', views.type_summary_year, name='typea'),
    # path('tsummary/<int:account_id>', views.type_summary_month, name='type'),
    # path('tsummary/<int:account_id>/<int:year>', views.type_summary_month, name='type'),
    path('tsummary/<int:account_id>/<int:year>/<int:month>', views.type_summary_month, name='type'),
    re_path('^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)$',
            views.statements,
            name='statements'),
    re_path('^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)$',
            views.statements,
            name='statements'),
    re_path('^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$',
            views.statements,
            name='statements'),
    re_path('^reports/(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)$',
            views.reports,
            name='reports'),
    re_path('^reports/(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)$',
            views.reports, name='reports'),
    path('statement/<int:statement_id>/',
         views.statement_edit,
         name='statement_edit'),
    path('statement/delete/<int:statement_id>',
         views.statement_delete,
         name='statement_delete'),
]

yect/yect/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.auth.views import LogoutView
from . import views

app_name = "yect"

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('bankbook/',
         include('bankbook.urls')),
    path('registration/',
         include('registration.urls')),
    path('admin/',
         admin.site.urls),
    path('',
         include('social_django.urls', namespace='social')),
    path('logout/',
         LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL),
         name='logout'), ]

yect/bankbook/models.py
from django.contrib.auth.models import User
from django.db import models, transaction
from django.db.models.signals import pre_save, post_save, post_delete, pre_delete
from django.dispatch import receiver
from django.db.models import F, Q
from django.utils.translation import gettext_lazy as _

from functools import reduce
import operator


class Bank(models.Model):
    name = models.CharField(max_length=200, help_text="Name of bank.")
    description = models.CharField(max_length=200, help_text="Description of bank.", blank=True, unique=False)

    def __str__(self):
        return self.name

    def create_bank(name, description):
        return Bank.objects.create(name=name, description=description)


class Account(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, help_text="Bank")
    account_number = models.CharField(max_length=200, help_text="Account number")
    name = models.CharField(max_length=200, help_text="Name of account")
    start_balance = models.DecimalField(max_digits=19, decimal_places=2, help_text="Initial balance of the account")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False, default=1)

    class Meta:
        unique_together = (('bank', 'account_number', 'owner'))

    def __init__(self, *args, **kwargs):
        super(Account, self).__init__(*args, **kwargs)
        self.__org_name = self.name
        self.__org_start_balance = self.start_balance

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.pk and (self.__org_name != self.name or self.__org_start_balance != self.start_balance):
            diff = self.start_balance - self.__org_start_balance
            if diff != 0:
                for summary in MonthSummaryCumulative.objects.filter(account__pk=self.pk):
                    summary.balance += diff
                    summary.excluded_balance += diff
                    summary.save()
                for summary in YearSummaryCumulative.objects.filter(account__pk=self.pk):
                    summary.balance += diff
                    summary.excluded_balance += diff
                    summary.save()
            for combine_item in CombineItem.objects.filter(account=self):
                combinedAccount = CombinedAccount.get_account_using_item(combine_item)
                if self.__org_name != self.name:
                    combinedAccount.create_sub_name()
            self.__org_name = self.name
            self.__org_start_balance = self.start_balance

    def __str__(self):
        return self.name + " : " + \
               self.bank.name + \
               " (" + self.account_number + " ) : " \
               + str(self.start_balance) + " : " + \
               self.owner.username

    def create_account(bank, account_number, name, start_balance, owner):
        return Account.objects.create(bank=bank,
                                      account_number=account_number,
                                      name=name,
                                      start_balance=start_balance,
                                      owner=owner)

    def get_accounts(user):
        return Account.objects.filter(owner=user).order_by('name')

    def get_account_by_id(id):
        return Account.objects.get(pk=id)

    def update_summaries(account, date):
        MonthSummaryCumulative.update_summaries(MonthSummaryCumulative, account, date)


class StatementType(models.Model):
    name = models.CharField(max_length=100, unique=False)
    description = models.CharField(max_length=300, unique=False)
    parent_type = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    sort_order = models.IntegerField(default=0, null=False, blank=False)

    def __str__(self):
        if self.parent_type is None or self.parent_type.pk == 20000 or self.parent_type.pk == 10000:
            return self.name
        else:
            return " -- " + self.name

    @staticmethod
    def create_statement_type(name, description, parent_type, sort_order):
        return StatementType.objects.create(name=name, description=description, parent_type=parent_type, sort_order=sort_order)

    @staticmethod
    def get_statement_types(names):
        return StatementType.objects.filter(reduce(operator.or_, [Q(name=n) for n in names]))

    @staticmethod
    def get_statement_types_by_id(id):
        return StatementType.objects.get(pk=id)


class Statement(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=19, decimal_places=2)
    exclude = models.BooleanField(default=False)
    date = models.DateField()
    text = models.CharField(max_length=200)
    type = models.ForeignKey(StatementType, on_delete=models.CASCADE, default=1)

    class Status(models.TextChoices):
        NEW = 'NEW', _('New')
        POSSIBLE_DUPLICATE = 'PD', _('Possible duplicate')
        SELF_SET = 'SF', _('Self set')
        AUTO_SET = 'AS', _('Auto Set')
        SKIP = 'SK', _('Skip')

    status = models.CharField(max_length=3, choices=Status.choices, default=Status.NEW)

    def __str__(self):
        return self.date.strftime("%Y-%m-%d") + ": " + str(self.amount) + " " + self.type.name + " " + self.status

    @transaction.atomic
    def update_summaries(account, date, amount, statement_type):
        while statement_type is not None:
            StatementTypeMonthSummary.update_month_summary(account=account, year=date.year, month=date.month,
                                                           statement_type=statement_type, amount=amount, exclude_amount=0)
            StatementTypeYearSummary.update_year_summary(account=account, year=date.year,
                                                         statement_type=statement_type, amount=amount, exclude_amount=0)

            statement_type = statement_type.parent_type

        recreate_month = MonthSummaryCumulative.update_month_summary(account, date.year, date.month, amount, 0)
        recreate_year = YearSummaryCumulative.update_year_summary(account, date.year, amount, 0)

    @transaction.atomic
    def insert_multiple_statements(account, statement_list):
        for (amount, date, text, statement_type) in statement_list:
            Statement.objects.create(account=account, amount=amount, date=date, text=text, type=statement_type)

    @transaction.atomic
    def create_statement(account, amount, date, text, statement_type):
        return Statement.objects.create(account=account, amount=amount, date=date, text=text, type=statement_type)

    @staticmethod
    def get_statements(accounts, year=None, month=None, day=None):
        if year is None and month is None and day is None:
            return Statement.objects.filter(reduce(operator.or_,
                                                   [Q(account=a)
                                                    for a in accounts])).order_by('-date', '-pk')
        if year is not None and month is None and day is None:
            return Statement.objects.filter(reduce(operator.or_,
                                                   [Q(date__year=year, account=a)
                                                    for a in accounts])).order_by('-date', '-pk')
        elif year is not None and month is not None and day is None:
            return Statement.objects.filter(reduce(operator.or_,
                                                   [Q(date__year=year, date__month=month, account=a)
                                                    for a in accounts])).order_by('-date', '-pk')
        elif year is not None and month is not None and day is not None:
            return Statement.objects.filter(reduce(operator.or_,
                                                   [Q(date__year=year, date__month=month, date__day=day, account=a)
                                                    for a in accounts])).order_by('-date', '-pk')
        else:
            raise Exception("Incorrect input")


class BaseMonthSummaryCumulative(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    year = models.IntegerField()
    month = models.IntegerField()
    balance = models.DecimalField(max_digits=19, decimal_places=2, default=0)
    excluded_balance = models.DecimalField(max_digits=19, decimal_places=2, default=0)

    class Meta:
        abstract = True
        unique_together = (('account', 'year', 'month'))

    def __str__(self):
        return str(self.year) + "-" + str(self.month) + ": " + str(self.balance)

    def create_month_summary_cumulative(summary_type, account, year, month, balance, excluded_balance):
        return summary_type.objects.create(account=account,
                                           year=year,
                                           month=month,
                                           balance=balance,
                                           excluded_balance=excluded_balance)

    def update_month_summary(summary_type, account, year, month, amount, exclude_amount):
        month_summary_cumulative, month_summary_cumulative_created = summary_type.objects.get_or_create(
            account=account, year=year, month=month,
            defaults={'account': account, 'year': year, 'month': month, 'balance': amount, 'excluded_balance': exclude_amount},
        )
        if not month_summary_cumulative_created:
            month_summary_cumulative.balance += amount
            month_summary_cumulative.save()
            next_entries = summary_type.objects.filter(
                reduce(operator.or_, [Q(account=account, year=year, month__gt=month),
                                      Q(account=account, year__gt=year)])).order_by('year', 'month')
            for entry in next_entries:
                entry.balance += amount
                entry.save()
            return False
        else:
            previous_entry = summary_type.objects.filter(

yect/bankbook/templates/bankbook/account_summary.html
{% extends "base.html" %}
{% load static %}

{% block title %}
YECT: type Summary
{% endblock %}

{% block head_script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="{% static "bankbook/js/stacked_area_chart.js" %}"></script>
    <script src="{% static "bankbook/js/horizontal_bar_plots.js" %}"></script>
<script src="{% static "bankbook/js/utils.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.6/nv.d3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.js"></script>
{% endblock %}

{% block head_link %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.6/nv.d3.css">
{% endblock %}


{% block content %}
<div id="index-banner" class="parallax-container bottom-border">
<div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-darken-4"> {{ account_name }}</h1>
            {% if included_accounts %}
            <div class="center">
                <h6 class="header col s12 teal-text text-darken-4">{{ included_accounts }}</h6>
            </div>
            {% endif %}
            <div class="row center">
                <h5 class="header col s12 teal-text text-darken-4">summary</h5>
            </div>
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="{% static "img/grid.png" %}" alt="Grid image"></div>
</div>

<div class="container">
    <div class="section">
        <div class="row center">
            <a class="dropdown-trigger btn-small waves-effect" href="#!" data-target="select_year">{{ selected_year }}</a>
            <ul id='select_year' class='dropdown-content'>
                {% for year in year_list  %}
                    <li><a href="{% url 'bankbook:account_summary' account_type=account_type account_id=account_id year=year %}">{{ year }}</a></li>
                {% endfor %}
            </ul>

            <a href="{% url 'bankbook:edit_account' account_type=account_type account_id=account_id %}"><i class="material-icons right small">settings</i></a>
        </div>
        <div class="row">
            <div id="summary_plot">
                <svg style="width:100%;height:400px"></svg>
            </div>
            <script>stackedAreaChart(addMissingTimeEvents({{ summary|safe }}),'#summary_plot svg',"%Y %b");</script>
        </div>
    </div>
</div>

  {% for m, d in month.items %}
<div id="index-banner" class="parallax-container top-border bottom-border">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="{% static "img/grid.png" %}" alt="Grid image"></div>
</div>
<div class="container">
    <div class="section">
        <div class="row">
            <h4 class="center teal-text text-darken-4">{{ m }}</h4>
        </div>
        <div class="row">
            <div class="col s12 m2 z-depth-1">
                <h5 class="center">Balance</h5>
                <p class="center">{{ d.balance }}</p>
            </div>
            <div class="col s12 m2 z-depth-1">
                <h5 class="center">Income</h5>
                <p class="center">{{ d.income.balance }}</p>
            </div>
            <div class="col s12 m2 z-depth-1">
                <h5 class="center">Expense</h5>
                <p class="center">{{ d.expense.balance }}</p>
            </div>
            <div class="col s12 m2 z-depth-1">
                <h5 class="center">Savings</h5>
                <p class="center">{{ d.saving.balance }}</p>
            </div>
            <div class="col s12 m2 z-depth-1">
                <h5 class="center">Transaction</h5>
                <p class="center">{{ d.transaction.balance }}</p>
            </div>
            <div class="col s12 m2 z-depth-1">
                <h5 class="center">Unknown</h5>
                <p class="center">{{ d.unknown.balance }} </p>
            </div>
        </div>
        <div class="row">
          <div id="summary_plot{{ m }}">
             <b></b>
              <svg style="width:100%;height:400px"></svg>
          </div>
      <script>createHorizontal({{ d.expense_type|safe }},'#summary_plot{{ m }} svg');</script>
<br />
        </div>
        <div class="row center">
            <a  href="{% url 'bankbook:statements' account_type=account_type account_id=account_id year=d.year month=d.month %}" class="waves-effect waves-light btn-large">Detailed information</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

yect/bankbook/templates/bankbook/edit_account.html
{% extends "base.html" %}
{% load static %}

{% block title %}
YECT: edit
{% endblock %}

{% block content %}
<div id="index-banner" class="parallax-container bottom-border">
<div class="section no-pad-bot">
        <div class="container">
            <br><br>
            {% if account_id %}
            <h1 class="header center teal-text text-darken-4"> {{ account_name }} </h1>
            {% else %}
            <h1 class="header center teal-text text-darken-4"> New </h1>
            {% endif %}
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="{% static "img/grid.png" %}" alt="Grid image"></div>
</div>

<div class="container">
{% if combined_account_form %}
    {% if account_form %}
    <div class="section">
        <div class="row">
            <form>
                <label>
                    <input group="type1" type="radio" id="account_type" name="account" onclick="javascript:accountType();" checked>
                    <span>Regular</span>
                </label>
                 <label>
                     <input group="type1" type="radio" id="combinedaccount_type" name="account" onclick="javascript:accountType();">
                     <span>Combined</span>
                 </label>
            </form>
        </div>
    </div>
    {% endif %}
{% endif %}

{% if account_form %}
    <div class="section" id="account_form">
        <form class="col s12" name="account" id="account" method="post">
            {% csrf_token %}
            {{ account_form.non_field_errors }}
            {{ account_form.owner }}
            <div class="row">
                <div class="input-field col s6">

                    {{ account_form.bank }}
                    {{ account_form.bank.errors }}
                    {% if account_form.bank.help_text %}
                    <small>
                        <span id="helpBlock" class="help-block">{{ account_form.bank.help_text|safe }}</span>
                    </small>
                    {% endif %}
                    <label for="id_bank" class="active">Bank: </label>
                </div>
                <div class="input-field col s6">
                    <label for="id_account_number" >Account number: </label>
                    {{ account_form.account_number }}
                    {{ account_form.account_number.errors }}
                    {% if account_form.account_number.help_text %}
                    <small>
                        <span id="helpBlock" class="help-block">{{ account_form.account_number.help_text|safe }}</span>
                    </small>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label for="id_name" >Name: </label>
                    {{ account_form.name }}
                    {{ account_form.name.errors }}
                    {% if account_form.name.help_text %}
                    <small>
                        <span id="helpBlock" class="help-block">{{ account_form.name.help_text|safe }}</span>
                    </small>
                    {% endif %}
                </div>
                <div class="input-field col s6">
                    <label for="id_start_balance">Start balance: </label>
                    {{ account_form.start_balance }}
                    {{ account_form.start_balance.errors }}
                    {% if account_form.start_balance.help_text %}
                    <small>
                        <span id="helpBlock" class="help-block">{{ account_form.start_balance.help_text|safe }}</span>
                    </small>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 center">
                    <input class="btn btn-primary" type="submit" value="Save" name="save_account" />
                </div>
            </div>
        </form>
    </div>
{% endif %}
{% if combined_account_form %}
    <div class="section" id="combineaccount_form">
        <form action="" name="combinedAccount" id="combinedaccount" method="post">
            {% csrf_token %}
            {{ combined_account_form.owner }}
            {% if combined_account_form.non_field_errors %}
            <div class="alert alert-warning">
                {{ combined_account_form.non_field_errors }}
            </div>
            {% endif %}
            <div class="row" id="combinedaccount_form" {% if account_form %} style="display:none" {% endif %}>
                <div class="input-field col s10">
                    <label for="id_name" class="active">Name: </label>
                    {{ combined_account_form.name }}
                    {{ combined_account_form.name.errors }}
                    {% if combined_account_form.name.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ combined_account_form.name.help_text|safe }}</span>
                        </small>
                    {% endif %}
                </div>

                <div class="col s10">
                    <h6>Accounts</h6>
                </div>
                {{ combined_item_formset.management_form }}
                {% for form in combined_item_formset.forms %}
                <div class="col s12">
                    <div class="input-field">
                        <div class="combine-item-formset">
                            <label for="id_account" class="active">Account: </label>
                            {{ form.account }}
                            {{ form.account.errors }}
                            {% if form.name.help_text %}
                                <small>
                                    <span id="helpBlock" class="help-block">{{ form.name.help_text|safe }}</span>
                                </small>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% if combined_item_formset.non_form_errors %}
                    {% for error in combined_item_formset.non_form_errors %}
                    <div class="alert alert-warning">
                        {{ error|escape }}
                    </div>
                    {% endfor %}
                {% endif %}

                <div class="col s12 right">
                    <input class="btn btn-primary pull-right" type="submit" value="Save" name="save_combinedaccount" />
                </div>
                <div style="clear: both;"></div>
            </div>
        </form>
    </div>
{% endif %}
</div>
{% endblock %}

{% block endscript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>

{% if combined_account_form %}
    {% if account_form %}
<script type="text/javascript">
function accountType() {
    if (document.getElementById('account_type').checked) {
        document.getElementById('account_form').style.display = 'block';
        document.getElementById('combinedaccount_form').style.display = 'none';
    } else {
        document.getElementById('account_form').style.display = 'none';
        document.getElementById('combinedaccount_form').style.display = 'block';
    }
}
</script>
    {% endif %}
{% endif %}

<script>
    $('.combine-item-formset').formset({
        addText: 'add account',
        deleteText: 'remove',
        added: function() {$('select').formSelect()}
    });
</script>

<script>
$(document).ready(function() {
    $('select').formSelect();
  });
</script>

<script>
    $('#formset').on('formAdded', function(event) {
    newForm = event.target;
    $('select').formSelect();
});
</script>
{% endblock %}

yect/bankbook/templates/bankbook/edit_statement.html
{% extends "base.html" %}
{% load static %}

{% block title %}
YECT: edit
{% endblock %}

{% block content %}
<div id="index-banner" class="parallax-container bottom-border">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            {% if account_name %}
            <h1 class="header center teal-text text-darken-4"> {{ account_name }} </h1>
            <div class="row center">
                <h5 class="header col s12 teal-text text-darken-4">statements</h5>
            </div>
            {% else %}
            <h1 class="header center teal-text text-darken-4"> New </h1>
            {% endif %}
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="{% static "img/grid.png" %}" alt="Grid image"></div>
</div>

<div class="container">
    <div class="section">
        <form id="id_statementform" action="" method="post" class="form-horizontal form-label-left">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row">
                <div class="input-field col s12">
                    <label for="id_date">Date: </label>
                    {{ form.date }}
                    {{ form.date.errors }}
                    {% if form.date.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ form.date.help_text|safe }}</span>
                        </small>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    <label for="id_text">Text: </label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    {% if form.text.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ form.text.help_text|safe }}</span>
                        </small>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    <label for="id_amount">Amount: </label>
                    {{ form.amount }}
                    {{ form.amount.errors }}
                    {% if form.amount.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ form.amount.help_text|safe }}</span>
                        </small>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    <label for="id_account" class="active">Account: </label>
                    <input readonly="readonly" type="text" value="{{ account_name }}" />
                    <input id="id_account" name="account" readonly="readonly" type="hidden" value="{{ form.account.value }}" required />
                    {{ form.account.errors }}
                    {% if form.account.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ form.account.help_text|safe }}</span>
                        </small>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <label for="id_type"  class="active">Type: </label>
                    <select class="custom-form-select" id="id_type" name="type" required>
                    {% for type in form.type.field.choices %}
                        {% if type.0 == 20000 %}
                            </optgroup>
                            <optgroup label="{{ type.1 }}">
                        {% elif type.0 == 15000 %}
                            </optgroup>
                            <optgroup label="{{ type.1 }}">
                        {% elif type.0 == 10000 %}
                            <optgroup label="{{ type.1 }}">
                        {% else %}
                            {% if type.2 %}
                            <option style="margin-left:30px;" {% if form.type.initial and form.type.initial == type.0%} selected {% endif %} value="{{ type.0 }}">MMM{{ type.1 }}</option>
                            {% else %}
                                <option style="margin-left:30px;" {% if form.type.initial and form.type.initial == type.0%} selected {% endif %} value="{{ type.0 }}">{{ type.1 }}</option>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                        </optgroup>
                    </select>
                    {{ form.type.errors }}
                    {% if form.type.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ form.type.help_text|safe }}</span>
                        </small>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <label>
                    {{ form.exclude }}
                    {{ form.exclude.errors }}
                    {% if form.exclude.help_text %}
                        <small>
                            <span id="helpBlock" class="help-block">{{ form.exclude.help_text|safe }}</span>
                        </small>
                    {% endif %}
                    <span>Exclude</span> </label>
                </div class="col s12">
            </div>
            <div class="row">
                <div class="col s6">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Save</button>
                </div>
                <div class="col s6 right-align">
                    <a href="{% url 'bankbook:statement_delete' statement_id=statement_id %}" class="btn btn-primary red" >DELETE</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block endscript %}

{% endblock %}