yect/bankbook/urls.py
from django.urls import path, re_path

from . import views

app_name = "bankbook"
urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('',
         views.statements,
         name='statements'),
    path('new',
         views.edit_account,
         name='new_account'),
    path('edit/<str:account_type><int:account_id>',
         views.edit_account,
         name='edit_account'),
    re_path(r'^upload/(?P<account_type>[a]{1})(?P<account_id>[0-9]+)$',
            views.upload_statements,
            name='upload_statements'),
    re_path(r'^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)$',
            views.account_summary,
            name='account_summary'),
    re_path(r'^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)$',
            views.account_summary,
            name='account_summary'),
    # path('csummarya/', views.cum_summary_year, name='cumulative_a'),
    # path('csummarya/<int:year>', views.cum_summary_year, name='cumulative_a'),
    # path('csummary/<int:year>', views.cum_summary_month, name='cumulative'),
    # path('csummary/<int:year>/<int:month>', views.cum_summary_month, name='cumulative'),
    # path('tsummarya/<int:account_id>', views.type_summary_year, name='typea'),
    # path('tsummarya/<int:account_id>/<int:year>', views.type_summary_year, name='typea'),
    # path('tsummary/<int:account_id>', views.type_summary_month, name='type'),
    # path('tsummary/<int:account_id>/<int:year>', views.type_summary_month, name='type'),
    path('tsummary/<int:account_id>/<int:year>/<int:month>', views.type_summary_month, name='type'),
    re_path('^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)$',
            views.statements,
            name='statements'),
    re_path('^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)$',
            views.statements,
            name='statements'),
    re_path('^(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$',
            views.statements,
            name='statements'),
    re_path('^reports/(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)$',
            views.reports,
            name='reports'),
    re_path('^reports/(?P<account_type>[ac]{1})(?P<account_id>[0-9]+)/(?P<year>[0-9]+)$',
            views.reports, name='reports'),
    path('statement/<int:statement_id>/',
         views.statement_edit,
         name='statement_edit'),
    path('statement/delete/<int:statement_id>',
         views.statement_delete,
         name='statement_delete'),
]

yect/yect/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.auth.views import LogoutView
from . import views

app_name = "yect"

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('bankbook/',
         include('bankbook.urls')),
    path('registration/',
         include('registration.urls')),
    path('admin/',
         admin.site.urls),
    path('',
         include('social_django.urls', namespace='social')),
    path('logout/',
         LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL),
         name='logout'), ]

yect/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <title>{% block title %}YECT{% endblock %}</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block head_link %}{% endblock %}

    {% block head_script %}{% endblock %}
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@materializecss/materialize@1.1.0-alpha/dist/css/materialize.min.css">
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>

</head>
<body>
    <ul id="dropdown1" class="dropdown-content">
        {% if accounts %}
        {% for account in accounts %}
        <li><a href="{% url 'bankbook:account_summary' account_type='a' account_id=account.id year=current_year %}">{{ account.name }}</a></li>
        {% endfor %}
        <li class="divider"></li>
        {% endif %}
        {% if accounts_combined %}
        {% for account in accounts_combined %}
        <li><a href="{% url 'bankbook:account_summary' account_type='c' account_id=account.id year=current_year %}">{{ account.name }}</a></li>
        {% endfor %}
        <li class="divider"></li>
        {% endif %}
        {% if accounts_shared %}
        <li>Shared accounts</li>
        <li class="divider"></li>
        {% endif %}
        <li><a href="{% url 'bankbook:new_account' %}">New<i class="material-icons tiny right">add</i></a></li>
        <!--<li><a href="#!">Combined<i class="material-icons tiny right">add</i></a></li>-->
    </ul>
    <nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="#" class="brand-logo">YECT</a>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="#">Navbar Link</a></li>
                {% if user.is_authenticated %}
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Accounts<i class="material-icons right">arrow_drop_down</i></a></li>
                <li>
                {% endif %}
            {% if user.is_authenticated %}
                <a class="btn btn-primary mt-5" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Login</a>
            {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
        <li class="divider"></li>
        <li><a class="subheader">Accounts</a></li>
        {% if accounts %}
        {% for account in accounts %}
        <li><a href="{% url 'bankbook:edit_account' account_type='a' account_id=account.id %}">{{ account.name }}</a></li>
        {% endfor %}
        <li class="divider"></li>
        {% endif %}
        {% if accounts_combined %}
        {% for account in accounts_combined %}
        <li><a href="{% url 'bankbook:edit_account' account_type='c' account_id=account.id %}">{{ account.name }}</a></li>
        {% endfor %}
        <li class="divider"></li>
        {% endif %}
        {% if accounts_shared %}
        <li>Shared accounts</li>
        <li class="divider"></li>
        {% endif %}
        <li><a href="bankbook/new">New<i class="material-icons tiny right">add</i></a></li>
        <!--<li><a href="#!">Combined<i class="material-icons tiny right">add</i></a></li>-->
        </ol>
    </ul>

    {% block content %}
    <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
            <div class="container">
                <br><br>
                <h1 class="header center teal-text text-darken-4">YECT</h1>
                <div class="row center">
                    <h5 class="header col s12 teal-text">Your Economy Control Tool</h5>
                </div>
                <div class="row center">
                    <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
                </div>
                <br><br>
            </div>
        </div>
        <div class="parallax"><img src="{% static "img/grid.png" %}" alt="Grid image"></div>
    </div>

    <div class="container">
        <div class="section">
            <div class="row">
                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center teal-text text-darken-4"><i class="material-icons">child_care</i></h2>
                        <h5 class="center">Easy and simple</h5>

                        <p class="light">Easy to use ... bla bla bla bla bla bla bla bla bla</p>
                    </div>
                </div>
                <div class="col s12 m4">
                     <div class="icon-block">
                        <h2 class="center teal-text text-darken-4"><i class="material-icons">share</i></h2>
                        <h5 class="center">Share data</h5>

                        <p class="light">Easy to use ... bla bla bla bla bla bla bla bla bla</p>
                    </div>
                </div>
                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center teal-text text-darken-4"><i class="material-icons">folder</i></h2>
                        <h5 class="center">Budget & reports</h5>

                        <p class="light">Easy to use ... bla bla bla bla bla bla bla bla bla</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
            <div class="container">
                <br><br>
                <h1 class="header center teal-text text-darken-4">It should be easy</h1>
            </div>
        </div>
        <div class="parallax"><img src="{% static "img/grid.png" %}" alt="Grid image"></div>
    </div>
    {% endblock %}

<footer class="page-footer teal darken-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Company Bio</h5>
                <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>

            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Settings</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% block endscript %}{% endblock %}

<script src="{% static "js/init.js"  %}"></script>


<script src="https://cdn.jsdelivr.net/npm/@materializecss/materialize@1.1.0-alpha/dist/js/materialize.min.js"></script>

</body>
</html>